stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - pip install git+https://github.com/pmgagne/tkinterdnd2
  - pyinstaller -F -w pdf-multi-tools\pdfmultitools.pyw --additional-hooks-dir=.

staging:
  stage: deploy
  script:
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - pip install git+https://github.com/pmgagne/tkinterdnd2
  - pyinstaller -F -w pdf-multi-tools\pdfmultitools.pyw --additional-hooks-dir=.
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - pip install git+https://github.com/pmgagne/tkinterdnd2
  - pyinstaller -F -w pdf-multi-tools\pdfmultitools.pyw --additional-hooks-dir=.
  only:
  - tags